# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml up

services:

  # wireshark:
  #   image: lscr.io/linuxserver/wireshark
  #   cap_add:
  #     - NET_ADMIN
  #   network_mode: service:husarnet-pc
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London

  rviz:
    image: husarion/rviz2:galactic
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./rosbot_pro.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID=2

  listener:
    build: .
    environment:
      - ROS_DOMAIN_ID=2
    command: ros2 run demo_nodes_py listener

  dds-router-pc:
    image: husarnet/dds-router:experimental
    network_mode: service:husarnet-pc
    ipc: host
    # ipc: service:husarnet-pc
    environment:
      - DS_HOSTNAME=ds
    volumes:
      - ./router-config.pc.yaml:/config.yaml
    command: bash -c "wait_ds.sh && ddsrouter -c /config.yaml -r 10 -d"

  husarnet-pc:
    image: husarnet/husarnet
    ipc: host
    # ipc: shareable
    # ports:
    #   - 3000:3000 #wireshark
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rviz2
      - JOINCODE=${HUSARNET_JOINCODE}
