# Quick Start
# $ docker compose -f compose.rosbot.yaml up

services:

  rplidar:
    image: husarion/rplidar:galactic
    devices:
      - /dev/ttyUSB0
    environment:
      - ROS_DOMAIN_ID=1
    command: ros2 launch rplidar_ros2 rplidar_a3_launch.py inverted:=true

  talker:
    build: .
    environment:
      - ROS_DOMAIN_ID=1
    command: ros2 run demo_nodes_py talker

  dds-router-rosbot:
    image: husarnet/dds-router
    network_mode: service:husarnet-rosbot
    ipc: service:husarnet-rosbot
    environment:
      - DS_HOSTNAME=ds
    volumes:
      - ./router-config.client.yaml:/config.yaml
    command: bash -c "wait_ds.sh && ddsrouter -c /config.yaml -r 10 -d"

  husarnet-rosbot:
    image: husarnet/husarnet
    ipc: shareable
    volumes:
      - /var/lib/husarnet 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rosbot
      - JOINCODE=${HUSARNET_JOINCODE}

# =========

  dds-router-ds:
    image: husarnet/dds-router
    network_mode: service:husarnet-ds
    ipc: service:husarnet-ds
    environment:
      - DS_HOSTNAME=ds
    volumes:
      - ./router-config.server.yaml:/config.yaml
    command: bash -c "wait_ds.sh && ddsrouter -c /config.yaml -r 10 -d"

  husarnet-ds:
    image: husarnet/husarnet
    ipc: shareable
    volumes:
      - /var/lib/husarnet 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=ds
      - JOINCODE=${HUSARNET_JOINCODE}

