services:

  listener1:
    build: .
    restart: unless-stopped
    network_mode: service:husarnet-listener
    volumes: 
      - ./dds-config.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
    command: ros2 run demo_nodes_cpp listener

  listener2:
    build: .
    restart: unless-stopped
    network_mode: service:husarnet-listener
    volumes: 
      - ./dds-config.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
    command: ros2 run demo_nodes_cpp listener --ros-args -r chatter:=chatter2

  husarnet-listener:
    image: husarnet/husarnet
    restart: unless-stopped
    volumes:
      - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment: 
      - HOSTNAME=listener
    env_file: 
      - ./.env  # create .env file in the same folder
    